### ISSUE TITLE
RuntimeError: Click -- Python 3 -- ASCII encoding

### ISSUE THREAD

**Issue by ts468** [madjar/nox#19] opened 2015-02-03 17:00 UTC
Hi,

I'm trying to use nox on my NixOS unstable installation, but nox-review fails with:

RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
(full message: https://gist.github.com/ts468/d6235428c0ad052251d8)

Do you have an idea what the cause could be and how to work around it?

Many thanks!
Thomas

**Comment by madjar** [comment] 2015-02-09 14:13
Hello Thomas

It looks like we have reached the ugly corner case of the argument-parsing library (click).

Could you give me the values of the `LC_ALL` and `LANG` environment variables, in order to understand what is happening here?

**Comment by ts468** [comment] 2015-02-09 14:22
Hi Georges,

thank you very much for looking into it! LC_ALL is not defined, and LANG="en_US.UTF-8".

Please let me know if I can help.

**Comment by madjar** [comment] 2015-02-09 14:30
I have to confess I have no idea what is going on. Could you try setting `LC_ALL` to `en_US.UTF-8`. If that doesn't work, could you show me the part of your configuration.nix that's about locale ?

**Comment by ts468** [comment] 2015-02-09 14:47
I've set LC_ALL to the same value as LANG, but nothing changed. The part out of my nix configuration is:

# Internationalisation properties
i18n = {
  consoleFont = "${pkgs.terminus_font}/share/consolefonts/ter-i32n.pcf.gz";
  consoleKeyMap = "de-latin1-nodeadkeys";
  defaultLocale = "en_US.UTF-8";
  supportedLocales = [ "de_DE.UTF-8" "en_US.UTF-8" ];
};

Thanks!

**Comment by madjar** [comment] 2015-02-09 15:47
Could you start a python 3 shell (with the command `python3`), and run the following commands?
```
import locale
import codecs
print(locale.getpreferredencoding())
print(codecs.lookup(locale.getpreferredencoding()).name)
```

**Comment by ts468** [comment] 2015-02-09 15:54
Sure:
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> import codecs
>>> print(locale.getpreferredencoding())
ANSI_X3.4-1968
>>> print(codecs.lookup(locale.getpreferredencoding()).name)
ascii
>>>

**Comment by madjar** [comment] 2015-02-09 15:56
Okay, so the problem is that python thinks that your preferred encoding is "ANSI_X3.4-1968", and not "UTF-8". I have no idea why. Can you think of anything that could cause that on your machine?

**Comment by ts468** [comment] 2015-02-09 16:16
Well, not really to be honest. Where does the encoding in python derive from? From the environment variables?

I don't know if that makes sense, but is it possible to pack nox in a way that it brings a working environment with it? Either by e.g. wrapping nox with a shell script that clears the environment and only sets the minimally required variables, or by e.g. setting the encoding in the python program itself for example?

**Comment by madjar** [comment] 2015-02-09 16:24
Let's go down the rabbit hole : https://hg.python.org/cpython/file/dc820b44ce21/Lib/locale.py#l614.

In the same python shell as before, what does `locale.getdefaultlocale()` returns?

**Comment by ts468** [comment] 2015-02-09 16:32
Alright, I'm with you ;)

>>> locale.getdefaultlocale()
('en_US', 'UTF-8')

**Comment by madjar** [comment] 2015-02-09 17:19
And what about `locale.CODESET` (I believe this might be the relevant one).

**Comment by ts468** [comment] 2015-02-09 17:22
>>> locale.CODESET  
14

**Comment by madjar** [comment] 2015-02-09 17:23
Ok. I've got the same one. This is madness.

I'll let the universe sort itself out tonight, and I'll look into it tomorrow.

**Comment by ts468** [comment] 2015-02-09 17:25
Thank you very much for trying to solve to problem so far!

**Comment by madjar** [comment] 2015-03-03 15:04
Sorry, I kind of forgot you. Do you still have the problem ?

**Comment by ts468** [comment] 2015-03-12 17:45
Thanks for getting back to me! Unfortunately, yes, I still have the problem.

**Comment by madjar** [comment] 2015-03-18 16:21
I have to confess I'm have no idea what is happening, I guess we'll have to report this upstream.

If I write a minimal piece of code reproducing the example, would you be able to run it so we can open an issue on click's bug tracker ?

**Comment by ts468** [comment] 2015-03-19 10:25
@madjar, thanks for following it up! I've played around with my setup right now again, and it seems as nox-review works after I switched from BASH to ZSH. For me that's fine for now, but if you want to report the issue upstream nevertheless, I'm happy to test a minimal example.

**Comment by madjar** [comment] 2015-04-21 12:16
@ts468 Since this error message is displayed immediatly at launch, any basic program should have the same error. The example program display on click.pocoo.org should present the problem too.

To run the program, you might need a venv, which you can create like so: `pyvenv venv && venv/bin/pip install click`. You can then run a `example.py` script by running. `venv/bin/python example.py`. Don't hesitate to delete the `venv` duir when you are done.

**Comment by rsc1975** [comment] 2015-08-26 18:18
I suffered the same issue in Fedora 21 (Python 3.4.2), I'm my case, the problem is that my Terminal app (OSX) try to set the locale (es_ES.utf-8) on the remote host (Linux), but if the remote host has not installed the locale then python chooses the "ANSI_X3.4-1968", I found a workaround, that works fine in my linux hosts:

    import locale, codecs
    if codecs.lookup(locale.getpreferredencoding()).name == 'ascii':
         os.environ['LANG'] = 'en_US.utf-8'
    import click

By default my Linux distros install 'en_US.utf-8' (I'm working with Fedora on Amazon AWS), so this patch works fine, if not then does nothing.

**Comment by madjar** [comment] 2015-09-06 09:24
Hello.

Could you try with this minimal code (it's the example from http://click.pocoo.org), to confirm that it's the mere fact of using click in that context that make it crash.

```
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)

if __name__ == '__main__':
    hello()
```

**Comment by rsc1975** [comment] 2015-09-06 11:01
Hi @madjar, yes It's click code:

```python
$ python3 test_click.py 
Traceback (most recent call last):
  File "test_click.py", line 13, in <module>
    hello()
  File "/home/doxr/.local/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/doxr/.local/lib/python3.4/site-packages/click/core.py", line 655, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```


Actually their code is quite explicit: https://github.com/mitsuhiko/click/blob/master/click/core.py

```python
# If we are in Python 3, we will verify that the environment is
        # sane at this point of reject further execution to avoid a
        # broken script.
        if not PY2:
            try:
                import locale
                fs_enc = codecs.lookup(locale.getpreferredencoding()).name
            except Exception:
                fs_enc = 'ascii'
            if fs_enc == 'ascii':
                raise RuntimeError('Click will abort further execution '
                                   'because Python 3 was configured to use '
                                   'ASCII as encoding for the environment. '
                                   'Either switch to Python 2 or consult '
                                   'http://click.pocoo.org/python3/ '
                                   'for mitigation steps.')
```

The reason for that is to "avoid broken script", IMO the RuntimeError a bit excessive.

I've creates a StackOverflow question (without too much success) to find a better patch: http://stackoverflow.com/questions/32234393/encoding-issue-with-python3-and-click-package

The previous patch has a problem (I explain it in the SO question), the `click` "show_help" command fails due to shutils.get_terminal_size method, I had to apply a sort of monkey-patching to avoid it, and I  also opened a python bug asking to return the default value instead of a ValueError: http://bugs.python.org/issue24966 The issue is still "open".

**Comment by madjar** [comment] 2015-09-06 11:06
Okay, this seems to be a very thorny issue. I'll close it here because it's a problem with click, but I'm curious to see how this could be resolved.

**Closed by madjar** 2015-09-06 11:06 UTC

**Comment by phoebebright** [comment] 2015-09-13 14:09
Had the same problem running on Ubuntu 14 via OSX Terminal Client.
Solved by simply running:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

**Comment by csaftoiu** [comment] 2016-07-30 19:33
Had this issue when running a cron script which ran a program which used click.
Solved with `export LANG=en_US.UTF-8`

**Comment by debuggermalhotra** [comment] 2018-02-16 18:30
Just run this in your terminal:
export LC_ALL=en_us.UTF-8
export LANG=en_us.UTF-8

and you'll be good to go!

**Comment by jluttine** [comment] 2018-03-29 07:00
Could `nox` define these as default values if the environment variables haven't been defined just to avoid unnecessary runtime errors? Currently, `nox-review` doesn't work in a nix shell created with `nix-shell --pure -p nox`.

**Comment by stevekm** [comment] 2018-04-13 22:58
On my system (CentOS 6) the locale's names all seem to be spelled differently, I had to use this:

```
export LANG=en_US.utf8 
export LC_ALL=en_US.utf8
```

**Comment by vietvudanh** [comment] 2018-06-21 15:23
I have the same problem on MacOS. But the problem only on Pycharm. So I set the variable for the run as:
```
LANG=en_US.utf8 
LC_ALL=en_US.utf8
```
And it works.

**Comment by labike** [comment] 2018-07-15 12:31
@vietvudanh  hi guys, how set in Mac OS pycharm? I just get the error!
